console.log("DND5E-CALENDAR: calendar-debug.js loading");

export class CalendarDebug {
  static PREFIX = "[DnD5e-Calendar]";
  static enabled = false;

  static FLOW_STATE = {
    init: false,
    calendarSetup: false,
    worldTimeRegistered: false,
    dnd5eCalendar: null,
    currentDate: null,
    currentTime: null,
    currentWeather: null,
    currentSeason: null,
    currentMoonPhase: null,
    lastUpdateTime: 0,
    updateCount: 0
  };

  static init() {
    console.log("[DnD5e-Calendar] CalendarDebug.init() called");
    try {
      if (typeof game !== "undefined" && game.settings) {
        this.enabled = game.settings.get("dnd5e-calendar", "debugMode") ?? false;
      } else {
        console.log("[DnD5e-Calendar] game.settings not available, defaulting debug to true");
        this.enabled = true;
      }

      if (this.enabled) {
        this.master("CalendarDebug initialized - Master Debugger ACTIVE");
      }
    } catch (e) {
      console.error("[DnD5e-Calendar] CalendarDebug.init() error:", e);
      this.enabled = true;
    }
  }

  static setDebugMode(enabled) {
    this.enabled = enabled;
    if (enabled) {
      this.master(`Debug mode ENABLED at ${new Date().toISOString()}`);
    }
  }

  static _log(level, message, data = null) {
    if (!this.enabled) return;

    const timestamp = new Date().toISOString().split("T")[1].split(".")[0];
    const prefix = `${this.PREFIX} [${timestamp}] [${level}]`;

    if (data) {
      console.log(`${prefix} ${message}`, data);
    } else {
      console.log(`${prefix} ${message}`);
    }
  }

  static error(message, data = null) {
    this._log("ERROR", message, data);
  }

  static warn(message, data = null) {
    this._log("WARN", message, data);
  }

  static info(message, data = null) {
    this._log("INFO", message, data);
  }

  static debug(message, data = null) {
    this._log("DEBUG", message, data);
  }

  static trace(message, data = null) {
    if (!this.enabled) return;
    console.trace(`${this.PREFIX} [TRACE] ${message}`, data);
  }

  static table(data, label = "Table") {
    if (!this.enabled) return;
    console.log(`${this.PREFIX} [TABLE] ${label}:`, data);
  }

  static group(label) {
    if (!this.enabled) return;
    console.group(`${this.PREFIX} [GROUP] ${label}`);
  }

  static groupEnd() {
    if (!this.enabled) return;
    console.groupEnd();
  }

  static groupCollapsed(label) {
    if (!this.enabled) return;
    console.groupCollapsed(`${this.PREFIX} [GROUP] ${label}`);
  }

  static master(message, data = null) {
    if (!this.enabled) return;

    const fullState = {
      ...this.FLOW_STATE,
      timestamp: new Date().toISOString(),
      uptime: Date.now() - this.FLOW_STATE.lastUpdateTime
    };

    console.log(`${this.PREFIX} [MASTER] ${message}`, data || fullState);
  }

  static trackInit(stage, success, details = null) {
    this.FLOW_STATE.init = success;
    this.master(`INIT: ${stage}`, details);
  }

  static trackCalendarSetup(calendar, success) {
    this.FLOW_STATE.calendarSetup = success;
    this.FLOW_STATE.dnd5eCalendar = calendar?.name || "unknown";
    this.master(`CALENDAR SETUP: ${success ? "SUCCESS" : "FAILED"}`, { calendar: this.FLOW_STATE.dnd5eCalendar });
  }

  static trackWorldTime(worldTime, delta, options, success) {
    this.FLOW_STATE.worldTimeRegistered = success;
    this.FLOW_STATE.lastUpdateTime = Date.now();
    this.FLOW_STATE.updateCount++;

    const flow = {
      worldTime: worldTime,
      delta: delta,
      options: options,
      midnights: options?.dnd5e?.deltas?.midnights || 0,
      isNewDay: (options?.dnd5e?.deltas?.midnights > 0 || delta >= 86400),
      flowState: this.FLOW_STATE,
      updateNumber: this.FLOW_STATE.updateCount
    };

    this.master(`TIME UPDATE: ${success ? "PROCESSED" : "FAILED"}`, flow);
  }

  static trackDateChange(oldDate, newDate, success) {
    this.FLOW_STATE.currentDate = newDate;
    this.master(`DATE CHANGE: ${success ? "UPDATED" : "FAILED"}`, { old: oldDate, new: newDate });
  }

  static trackTimeChange(oldTime, newTime, success) {
    this.FLOW_STATE.currentTime = newTime;
    this.master(`TIME CHANGE: ${success ? "UPDATED" : "FAILED"}`, { old: oldTime, new: newTime });
  }

  static trackWeatherChange(oldWeather, newWeather, mode, success) {
    this.FLOW_STATE.currentWeather = newWeather;
    this.master(`WEATHER CHANGE: ${success ? "UPDATED" : "FAILED"}`, {
      old: oldWeather,
      new: newWeather,
      mode: mode,
      autoGenerated: mode === "auto"
    });
  }

  static trackSeasonChange(oldSeason, newSeason, success) {
    this.FLOW_STATE.currentSeason = newSeason;
    this.master(`SEASON CHANGE: ${success ? "UPDATED" : "FAILED"}`, {
      old: oldSeason,
      new: newSeason
    });
  }

  static trackMoonPhase(oldPhase, newPhase, dayCount, success) {
    this.FLOW_STATE.currentMoonPhase = newPhase;
    this.master(`MOON PHASE CHANGE: ${success ? "UPDATED" : "UNCHANGED"}`, {
      old: oldPhase,
      new: newPhase,
      dayCount: dayCount
    });
  }

  static trackHook(hookName, payload, success) {
    this.master(`HOOK FIRED: ${hookName}`, { payload: payload, success: success });
  }

  static trackStateSync(state, success) {
    this.master(`STATE SYNC: ${success ? "SYNCED" : "FAILED"}`, state);
  }

  static getFlowState() {
    return {
      ...this.FLOW_STATE,
      memory: window.performance?.memory ? {
        usedJSHeapSize: window.performance.memory.usedJSHeapSize,
        totalJSHeapSize: window.performance.memory.totalJSHeapSize
      } : null
    };
  }

  static printFlowState() {
    if (!this.enabled) return;
    console.log(`${this.PREFIX} [FULL FLOW STATE]:`, this.getFlowState());
  }

  static logHook(hookName, data) {
    this.debug(`Hook fired: ${hookName}`, data);
  }

  static logPermission(action, user, allowed) {
    this.debug(`Permission ${action}: ${user.name} (role: ${user.role}) -> ${allowed ? "ALLOWED" : "DENIED"}`);
  }

  static logSocket(action, data) {
    this.debug(`Socket ${action}`, data);
  }

  static logData(operation, path, value) {
    this.debug(`Data ${operation}: ${path}`, value);
  }
}

window.CalendarDebug = CalendarDebug;
